### ISSUE TITLE
Command Line Interface for nbparameterise

### ISSUE THREAD

**Issue by dokempf** [takluyver/nbparameterise#21]
I just wanted to let you know that I have played around with a [click](https://click.palletsprojects.com/en/8.0.x/)-based command line interface for `nbparameterise`. I have published the result under the name [nbclick](https://github.com/ssciwr/nbclick). It allows to modify and run notebooks directly from the command line. E.g. if this code cell is in `notebook.ipynb`:

```
num_samples = 1000      # The number of samples to draw
outfile = "output.csv"  # The filename to store the results
```

Then, `nbclick` will generate the following CLI that automatically runs the notebook:

```
Usage: nbclick notebook.ipynb [OPTIONS]

Options:
  --num_samples INTEGER  The number of samples to draw  [default: 1000]
  --outfile TEXT         The filename to store the results  [default:
                         output.csv]
  --help                 Show this message and exit.
```

If you are interested, the code for `nbclick` could be incorporated directly into `nbparameterise` (it is [~50 lines of code](https://github.com/ssciwr/nbclick/blob/main/nbclick/__main__.py)). If you prefer to have it separate, it would be cool to link to it from the `nbparameterise`'s README.

**Comment by takluyver** [comment]
Nice! I think I'd be inclined to leave it separate, so nbparameterise is just focused on the Python API. I'm old-fashioned enough that I like to avoid extra dependencies. :smile: I'd be happy to have a link in the README, though.

We have some internal code (at [European XFEL](https://www.xfel.eu/)) which does something similar but built around argparse. It's nothing really secret, but it's kind of messy because it's tied up in a larger system. But one bit you might be interested in is that we turn boolean parameters into pairs of flags like `--foo` and `--no-foo`. Here's the relevant bit of code:

```python
elif issubclass(p.type, bool):
    # For a boolean, make --XYZ and --no-XYZ options.
    alt_group = pars_group.add_mutually_exclusive_group(required=required)
    alt_group.add_argument(f"--{consolize_name(p.name)}",
                           action="store_true",
                           default=default,
                           help=helpstr,
                           dest=p.name)
    alt_group.add_argument(f"--no-{consolize_name(p.name)}",
                           action="store_false",
                           default=default,
                           help=f"Opposite of --{consolize_name(p.name)}",
                           dest=p.name)
```

Undoubtedly something similar is possible with Click, though I don't know exactly how to write it. :slightly_smiling_face: 

(Our code also has another special case to turn ranges like `0-7` into lists of integers, but I think that probably doesn't make sense in a general tool.)

**Comment by takluyver** [comment]
BTW, I was working on some improvements to the parameter replacement and the Python API in #19. Then I found I was uncertain about how I wanted a couple of things to work, so I stopped to think about it and then forgot about it. If you have any thoughts, I'd be happy to hear them.

**Comment by dokempf** [comment]
I can also see the benefit of a separate tool, but I thought I'd give you the choice. Good feedback on the boolean switches - that is a very simple addition I will incorporate. Will have a look at #19.
