### ISSUE TITLE
exception swallowed

### ISSUE THREAD

**Issue by david-waterworth** [takluyver/nbparameterise#7]
Hi,

I don't know if this is intentional, but `/code_drivers/python.py` the `check_fillable_node` raises a ASTMismatch if the assignment isn't 'number, string or boolean'. However this seems to be swallowed by `ASTPatternFinder` so it cannot be caught.

    for assign in astsearch.ASTPatternFinder(definition_pattern).scan_ast(cell_ast):
        yield Parameter(assign.targets[0].id, *type_and_value(assign.value))

I noticed because I had the following assignment

timeout = 60*60

in my first cell and it wasn't being returned by `extract_parameters` and there was no error/warning.

It might break existing code to 'fix' this, and I guess it's hard to create patterns for an assignment from a constant expression like 60*60 but it would be nice if it worked.

**Comment by takluyver** [comment]
The intentionality is kind of in a grey zone - for astsearch it's certainly deliberate that it finds nodes matching a pattern and ignores others rather than throwing an error. For nbparameterise, it was just the easy way to write it - and as you say, someone is probably now depending on it ignoring other bits of code in that cell.

In principle it's easy enough to match only expressions with constants and operators based on the AST, although the recursive check might be a bit fiddly to write. Then I guess you could evaluate it to work out the type of the parameter - Python does something similar as an optimisation (constant folding) when it byte compiles a module. If it was necessary to avoid evaluating, you'd need rules for e.g. string * int -> string.

**Comment by david-waterworth** [comment]
Thanks, if I get time I'll take a closer look. I'd also like to create a basic language processor for R, maybe just using a simple regexp to parse the different types of assignments, i.e.

name <- value
value -> name
name = value
